/*
  Warnings:

  - The primary key for the `Product` table will be changed.
*/

-- Fix Product ID

ALTER TABLE "Product"
DROP CONSTRAINT "Product_pkey";

ALTER TABLE "Product"
ALTER COLUMN "id" DROP DEFAULT;

ALTER TABLE "Product"
ALTER COLUMN "id" SET DATA TYPE BIGINT;

ALTER TABLE "Product"
ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE "Product"
ADD CONSTRAINT "Product_pkey" PRIMARY KEY ("id");

-- Create User
CREATE TABLE "User" (
    "id" UUID NOT NULL,
    "email" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- Create Feedback
CREATE TABLE "Feedback" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "userId" UUID NOT NULL,
    "topic" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,
    "message" TEXT NOT NULL,
    "createdAt" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Feedback_pkey" PRIMARY KEY ("id")
);

-- Create CartItem
CREATE TABLE "CartItem" (
    "userId" UUID NOT NULL,
    "productId" BIGINT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 1,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CartItem_pkey" PRIMARY KEY ("userId","productId")
);

-- Create WishlistItem
CREATE TABLE "WishlistItem" (
    "userId" UUID NOT NULL,
    "productId" BIGINT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "WishlistItem_pkey" PRIMARY KEY ("userId","productId")
);

-- Indexes
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

CREATE INDEX "idx_feedbacks_user_id"
ON "Feedback"("userId");

-- Foreign Keys
ALTER TABLE "Feedback"
ADD CONSTRAINT "Feedback_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "User"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE "CartItem"
ADD CONSTRAINT "CartItem_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "User"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE "CartItem"
ADD CONSTRAINT "CartItem_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "Product"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE "WishlistItem"
ADD CONSTRAINT "WishlistItem_userId_fkey"
FOREIGN KEY ("userId")
REFERENCES "User"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE "WishlistItem"
ADD CONSTRAINT "WishlistItem_productId_fkey"
FOREIGN KEY ("productId")
REFERENCES "Product"("id")
ON DELETE CASCADE
ON UPDATE CASCADE;